const items = [
    {
        title: 'Tiki Bar 12 oz.',
        scent: 'A refreshing blend of coconut, pineapple, rum, tangerine, banana, and melon',
        price: '25',
        size: '12 oz.',
        burnTime: '110',
        slug: 'tiki-12oz',
        image: 'tiki-12oz.png',
        shippingWeight: 500,
    },
    {
        title: 'Tiki Bar 16 oz.',
        scent: 'A refreshing blend of coconut, pineapple, rum, tangerine, banana, and melon',
        price: '30',
        size: '16 oz.',
        burnTime: '140',
        slug: 'tiki-16oz',
        image: 'tiki-16oz.png',
        shippingWeight: 600,
    },
    {
        title: 'Cotton Bayou 12 oz.',
        scent: 'Scents of freshly washed linens dried outside on a breezy coastal afternoon',
        price: '25',
        size: '12 oz.',
        burnTime: '110',
        slug: 'cotton-12oz',
        image: 'cotton-12oz.png',
        shippingWeight: 500,
    },
    {
        title: 'Cotton Bayou 16 oz.',
        scent: 'Scents of freshly washed linens dried outside on a breezy coastal afternoon',
        price: '30',
        size: '16 oz.',
        burnTime: '140',
        slug: 'cotton-16oz',
        image: 'cotton-16oz.png',
        shippingWeight: 600,
    },
    {
        title: 'The Gulf 12 oz.',
        scent: 'Delicate floral and fruity blend with hints of rose, violet, peach, citrus, and strawberry',
        price: '25',
        size: '12 oz.',
        burnTime: '110',
        slug: 'gulf-12oz',
        image: 'gulf-12oz.png',
        shippingWeight: 500,
    },
    {
        title: 'The Gulf 16 oz.',
        scent: 'Delicate floral and fruity blend with hints of rose, violet, peach, citrus, and strawberry',
        price: '30',
        size: '16 oz.',
        burnTime: '140',
        slug: 'gulf-16oz',
        image: 'gulf-16oz.png',
        shippingWeight: 600,
    },
];

export default items;