const items = [
    {
        title: 'Tiki Bar 8 oz.',
        scent: 'A refreshing blend of coconut, pineapple, rum, tangerine, banana, and melon',
        price: '18.00',
        size: '8 oz.',
        slug: 'tiki-8oz',
        image: '/tiki-bar-candle.jpg',
        shippingWeight: 500,
    },
    {
        title: 'Cotton Bayou 8 oz.',
        scent: 'Scents of freshly washed linens dried outside on a breezy coastal afternoon',
        price: '18.00',
        size: '8 oz.',
        slug: 'cotton-8oz',
        image: '/tiki-bar-candle.jpg',
        shippingWeight: 500,
    },
    {
        title: 'The Gulf 8 oz.',
        scent: 'Delicate floral and fruity blend with hints of rose, violet, peach, citrus, and strawberry',
        price: '18.00',
        size: '8 oz.',
        slug: 'gulf-8oz',
        image: '/tiki-bar-candle.jpg',
        shippingWeight: 500,
    },
    {
        title: 'Tiki Bar 12 oz.',
        scent: 'A refreshing blend of coconut, pineapple, rum, tangerine, banana, and melon',
        price: '24.00',
        size: '12 oz.',
        slug: 'tiki-12oz',
        image: '/tiki-12oz.png',
        shippingWeight: 500,
    },
    {
        title: 'Cotton Bayou 12 oz.',
        scent: 'Scents of freshly washed linens dried outside on a breezy coastal afternoon',
        price: '24.00',
        size: '12 oz.',
        slug: 'cotton-8oz',
        image: '/tiki-bar-candle.jpg',
        shippingWeight: 500,
    },
    {
        title: 'The Gulf 12 oz.',
        scent: 'Delicate floral and fruity blend with hints of rose, violet, peach, citrus, and strawberry',
        price: '24.00',
        size: '12 oz.',
        slug: 'gulf-12oz',
        image: '/tiki-bar-candle.jpg',
        shippingWeight: 500,
    },
    {
        title: 'Tiki Bar 16 oz.',
        scent: 'A refreshing blend of coconut, pineapple, rum, tangerine, banana, and melon',
        price: '30.00',
        size: '16 oz.',
        slug: 'tiki-16oz',
        image: '/tiki-bar-candle.jpg',
        shippingWeight: 600,
    },
    {
        title: 'Cotton Bayou 16 oz.',
        scent: 'Scents of freshly washed linens dried outside on a breezy coastal afternoon',
        price: '30.00',
        size: '16 oz.',
        slug: 'cotton-16oz',
        image: '/tiki-bar-candle.jpg',
        shippingWeight: 600,
    },
    {
        title: 'The Gulf 16 oz.',
        scent: 'Delicate floral and fruity blend with hints of rose, violet, peach, citrus, and strawberry',
        price: '30.00',
        size: '16 oz.',
        slug: 'gulf-16oz',
        image: '/tiki-bar-candle.jpg',
        shippingWeight: 600,
    },
];

export default items;