// This file is generated by Sapper — do not edit it!
export const routes = [
	{ error: '4xx', load: () => import(/* webpackChunkName: "_4xx" */ '../../routes/4xx.html') },
	{ error: '5xx', load: () => import(/* webpackChunkName: "_5xx" */ '../../routes/5xx.html') },
	{ pattern: /^\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "_" */ '../../routes/index.html') },
	{ pattern: /^\/shop.json\/?$/, ignore: true },
	{ pattern: /^\/about\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "about" */ '../../routes/about.html') },
	{ pattern: /^\/shop\/?$/, params: () => ({}), load: () => import(/* webpackChunkName: "shop" */ '../../routes/shop/index.html') },
	{ pattern: /^\/shop(?:\/([^\/]+?).json)?\/?$/, ignore: true },
	{ pattern: /^\/shop(?:\/([^\/]+?))?\/?$/, params: match => ({ slug: match[1] }), load: () => import(/* webpackChunkName: "shop_$slug$" */ '../../routes/shop/[slug].html') }
];