// This file is generated by Sapper — do not edit it!
import _ from '../../routes/index.html';
import about from '../../routes/about.html';
import shop from '../../routes/shop/index.html';
import shop_$slug$ from '../../routes/shop/[slug].html';
import _4xx from '../../routes/4xx.html';
import _5xx from '../../routes/5xx.html';
import * as api_shop from '../../routes/api/shop/index.js';
import * as api_shop_$slug$ from '../../routes/api/shop/[slug].js';

export const routes = [
	{ id: '_', type: 'page', pattern: /^\/?$/, params: () => ({}), module: _ },
	{ id: 'about', type: 'page', pattern: /^\/about\/?$/, params: () => ({}), module: about },
	{ id: 'shop', type: 'page', pattern: /^\/shop\/?$/, params: () => ({}), module: shop },
	{ id: 'shop_$slug$', type: 'page', pattern: /^\/shop(?:\/([^\/]+?))?\/?$/, params: match => ({ slug: match[1] }), module: shop_$slug$ },
	{ error: '4xx', module: _4xx },
	{ error: '5xx', module: _5xx },
	{ id: 'api_shop', type: 'route', pattern: /^\/api\/shop\/?$/, params: () => ({}), module: api_shop },
	{ id: 'api_shop_$slug$', type: 'route', pattern: /^\/api\/shop(?:\/([^\/]+?))?\/?$/, params: match => ({ slug: match[1] }), module: api_shop_$slug$ }
];