// This file is generated by Sapper — do not edit it!
export const timestamp = 1522682282775;

export const assets = [
	"alabama.png",
	"android-icon-144x144.png",
	"android-icon-192x192.png",
	"android-icon-36x36.png",
	"android-icon-48x48.png",
	"android-icon-72x72.png",
	"android-icon-96x96.png",
	"apple-icon-114x114.png",
	"apple-icon-120x120.png",
	"apple-icon-144x144.png",
	"apple-icon-152x152.png",
	"apple-icon-180x180.png",
	"apple-icon-57x57.png",
	"apple-icon-60x60.png",
	"apple-icon-72x72.png",
	"apple-icon-76x76.png",
	"apple-icon-precomposed.png",
	"apple-icon.png",
	"beach.jpg",
	"bottle.png",
	"browserconfig.xml",
	"candle.png",
	"citrus-12oz.jpg",
	"citrus-16oz.jpg",
	"cotton-12oz.jpg",
	"cotton-16oz.jpg",
	"cotton-bayou-candle.jpg",
	"favicon-16x16.png",
	"favicon-32x32.png",
	"favicon-96x96.png",
	"favicon.ico",
	"flight.jpg",
	"global.css",
	"gulf-12oz.jpg",
	"gulf-16oz.jpg",
	"leaf.png",
	"logo.png",
	"manifest.json",
	"ms-icon-144x144.png",
	"ms-icon-150x150.png",
	"ms-icon-310x310.png",
	"ms-icon-70x70.png",
	"robots.txt",
	"tachyons.min.css",
	"tiki-12oz.jpg",
	"tiki-16oz.jpg",
	"tiki-bar-candle.jpg",
	"wooden-wick-candle.jpg"
];

export const shell = [
	"client/7413b73ad048c2884045/_~_4xx~_5xx~about~shop~shop_$slug$.0.js",
	"client/7413b73ad048c2884045/shop_$slug$.1.js",
	"client/7413b73ad048c2884045/shop.2.js",
	"client/7413b73ad048c2884045/about.3.js",
	"client/7413b73ad048c2884045/_.4.js",
	"client/7413b73ad048c2884045/_5xx.5.js",
	"client/7413b73ad048c2884045/_4xx.6.js",
	"client/7413b73ad048c2884045/main.js"
];

export const routes = [
	{ pattern: /^\/?$/ },
	{ pattern: /^\/about\/?$/ },
	{ pattern: /^\/shop\/?$/ },
	{ pattern: /^\/shop(?:\/([^\/]+?))?\/?$/ }
];