// This file is generated by Sapper — do not edit it!
import _4xx from '../../routes/4xx.html';
import _5xx from '../../routes/5xx.html';
import _ from '../../routes/index.html';
import * as shop_json from '../../routes/shop.json.js';
import about from '../../routes/about.html';
import shop from '../../routes/shop/index.html';
import * as shop_$slug$_json from '../../routes/shop/[slug].json.js';
import shop_$slug$ from '../../routes/shop/[slug].html';

export const routes = [
	{ error: '4xx', module: _4xx },
	{ error: '5xx', module: _5xx },
	{ id: '_', type: 'page', pattern: /^\/?$/, params: () => ({}), module: _ },
	{ id: 'shop_json', type: 'route', pattern: /^\/shop.json\/?$/, params: () => ({}), module: shop_json },
	{ id: 'about', type: 'page', pattern: /^\/about\/?$/, params: () => ({}), module: about },
	{ id: 'shop', type: 'page', pattern: /^\/shop\/?$/, params: () => ({}), module: shop },
	{ id: 'shop_$slug$_json', type: 'route', pattern: /^\/shop(?:\/([^\/]+?).json)?\/?$/, params: match => ({ slug: match[1] }), module: shop_$slug$_json },
	{ id: 'shop_$slug$', type: 'page', pattern: /^\/shop(?:\/([^\/]+?))?\/?$/, params: match => ({ slug: match[1] }), module: shop_$slug$ }
];