const items = [
    {
        title: "Mother's Day Candle Flight",
        scent: "These candles make a great gift for Mom! This candle flight includes three 4 oz. mini candles - you choose the scents.",
        details: "How to choose your scents:  Once you've purchased, a member of our Salty Seahorse Team will contact you via email to confirm your preferred scents.",
        price: '25',
        size: '4 oz.',
        burnTime: '40',
        slug: 'mothers-day-flight',
        image: 'flight.jpg',
        shippingWeight: 500,
        fullWidth: true
    },
    {
        title: 'Coastal Citrus 12 oz.',
        scent: 'Crisp, clean scents of blood orange and grapefruit - your daily dose of Vitamin "Sea"',
        price: '25',
        size: '12 oz.',
        burnTime: '110',
        slug: 'citrus-12oz',
        image: 'citrus-12oz.jpg',
        shippingWeight: 500,
    },
    {
        title: 'Coastal Citrus 16 oz.',
        scent: 'Crisp, clean scents of blood orange and grapefruit - your daily dose of Vitamin "Sea"',
        price: '30',
        size: '16 oz.',
        burnTime: '140',
        slug: 'citrus-16oz',
        image: 'citrus-16oz.jpg',
        shippingWeight: 600,
    },

    {
        title: 'Tiki Bar 12 oz.',
        scent: 'A refreshing blend of coconut, pineapple, rum, tangerine, banana, and melon',
        price: '25',
        size: '12 oz.',
        burnTime: '110',
        slug: 'tiki-12oz',
        image: 'tiki-12oz.jpg',
        shippingWeight: 500,
    },
    {
        title: 'Tiki Bar 16 oz.',
        scent: 'A refreshing blend of coconut, pineapple, rum, tangerine, banana, and melon',
        price: '30',
        size: '16 oz.',
        burnTime: '140',
        slug: 'tiki-16oz',
        image: 'tiki-16oz.jpg',
        shippingWeight: 600,
    },
    {
        title: 'Cotton Bayou 12 oz.',
        scent: 'Scents of freshly washed linens dried outside on a breezy coastal afternoon',
        price: '25',
        size: '12 oz.',
        burnTime: '110',
        slug: 'cotton-12oz',
        image: 'cotton-12oz.jpg',
        shippingWeight: 500,
    },
    {
        title: 'Cotton Bayou 16 oz.',
        scent: 'Scents of freshly washed linens dried outside on a breezy coastal afternoon',
        price: '30',
        size: '16 oz.',
        burnTime: '140',
        slug: 'cotton-16oz',
        image: 'cotton-16oz.jpg',
        shippingWeight: 600,
    },
    {
        title: 'The Gulf 12 oz.',
        scent: 'Delicate floral and fruity blend with hints of rose, violet, peach, citrus, and strawberry',
        price: '25',
        size: '12 oz.',
        burnTime: '110',
        slug: 'gulf-12oz',
        image: 'gulf-12oz.jpg',
        shippingWeight: 500,
    },
    {
        title: 'The Gulf 16 oz.',
        scent: 'Delicate floral and fruity blend with hints of rose, violet, peach, citrus, and strawberry',
        price: '30',
        size: '16 oz.',
        burnTime: '140',
        slug: 'gulf-16oz',
        image: 'gulf-16oz.jpg',
        shippingWeight: 600,
    },
];

export default items;